Dockerise frontend and question service
CS3219-AY2425S1/cs3219-ay2425s1-project-g25 pull request #40
Opened 2024-10-03 03:36 UTC by njxue

* Dockerised Frontend and Question Service (I saw wen jie already created a Dockerfile for User Service and Gateway Service)
* To modify after integrating with Gateway service:
   - `frontend` depends on `gateway-service` in docker-compose

2024-10-03 14:25 UTC, Nephelite approved these changes

2024-10-03 14:25 UTC, Nephelite commented on backend/question-service/package-lock.json
Note: Should eventually add package-lock.json to gitignore, we can leave this alone for now though.

2024-10-03 14:25 UTC, Nephelite commented on backend/question-service/models/Category.ts
>  }
I think the former method of extending and omitting from SharedCategory in alignment with CS3219 priorities of maintainability and scalability. If anything, Question.js should be changed to match this implementation.

2024-10-03 14:25 UTC, Nephelite commented on docker-compose.yml
> +version: "3.9"
This attribute is obsolete, even if CS3219 says that this is needed in their documentation.

2024-10-03 15:06 UTC, SPWwj commented on backend/question-service/Dockerfile
> +EXPOSE 3001
Change to port 3002

2024-10-03 15:15 UTC, SPWwj requested changes

2024-10-03 15:15 UTC, SPWwj commented on backend/question-service/Dockerfile
> +EXPOSE 3001
Change to port 3002

2024-10-03 15:15 UTC, SPWwj commented on docker-compose.yml
> +      - 3001:3001
change to port 3002

2024-10-03 15:29 UTC, njxue commented on backend/question-service/package-lock.json
Is there a reason why? Usually, package-lock.json should not be .gitignored though

2024-10-03 17:01 UTC, Nephelite commented on backend/question-service/package-lock.json
we just gitignore package-lock because the package.json tells npm i how to reconstruct it. By removing package-lock.json, you reduce the size of the github file.

2024-10-04 00:51 UTC, njxue commented on backend/question-service/package-lock.json
Hmm, FWIW, it's normally recommended to source control package lock because it ensures that everyone has the same version of the dependencies (package.json alone does not guarantee that)

2024-10-04 03:18 UTC, SPWwj approved these changes

2024-10-04 03:18 UTC, merged